[package]
name = "day10_pipe_maze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exrunner = { path = "../exrunner" }
phf = { version = "0.11.2", features = ["macros"] }
